### ISSUE TITLE
Latest Master Companion App Crash (XE24 + Android 11)

### ISSUE THREAD

**Issue by drraccoony** [tujson/GlassEcho#3]
First off, thanks a ton for making this. Tossed some money your way on Cash app.

I built and put the glass app and companion app on my devices (XE24). Android 11 on Google Pixel 2 XL. I can try and get a crash report(?). I just need to figure out how.

**Comment by drraccoony** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.synople.glassecho.phone, PID: 31063
    java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=dev.synople.glassecho.phone shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 actions=3 vis=PRIVATE)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:603)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:582)
        at android.app.NotificationManager.notify(NotificationManager.java:531)
        at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:215)
        at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:199)
        at dev.synople.glassecho.phone.fragments.HomeFragment.showNotification(HomeFragment.kt:122)
        at dev.synople.glassecho.phone.fragments.HomeFragment.access$showNotification(HomeFragment.kt:32)
        at dev.synople.glassecho.phone.fragments.HomeFragment$onViewCreated$$inlined$apply$lambda$2.onClick(HomeFragment.kt:62)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by tujson** [comment]
Ah, do you know what app sent that notification? The fix feels simple, just making the small icon nullable or so.

As a heads up (I'll add this to the README), I won't be able to work on this for the foreseeable future. I no longer have access to a pair of Glass (XE or EE 2).

**Comment by drraccoony** [comment]
> Ah, do you know what app sent that notification?
Actually the test notification button crashes it.
